"""add trade_no

Revision ID: 314590377de2
Revises: 4e3d23885569
Create Date: 2019-03-09 11:49:07.680787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314590377de2'
down_revision = '4e3d23885569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ys_order_info', sa.Column('trade_no', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ys_order_info', 'trade_no')
    # ### end Alembic commands ###
