"""add image_table

Revision ID: 500155d9dbb8
Revises: e116dd1beeeb
Create Date: 2019-03-06 10:59:43.509894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '500155d9dbb8'
down_revision = 'e116dd1beeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ys_hosue_image',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['ys_hosue_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ys_house_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ys_house_info',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('area_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('room_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('acreage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('beds', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('deposit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('min_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('index_image_url', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], [u'ys_area_info.id'], name=u'ys_house_info_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'ys_user_profile.id'], name=u'ys_house_info_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('ys_hosue_image')
    # ### end Alembic commands ###
